/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f808db82-0082-4df5-85b0-ed1d81ddf4c7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_b3TMYyiGr",
    "aws_user_pools_web_client_id": "352djnmp3g4t2s8hhtjjv899l8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://e225f62chbhpnpuyfsbmzaqhs4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
