/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fc89e407-b14e-4ebb-8a78-f6d8a3144250",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_I55Tjz3zF",
    "aws_user_pools_web_client_id": "4099opbkgt0v34rf8v5f0qlkha",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dpd25lfmhfevbcghfdlcx6bnd4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://96i480te1l.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
